#!/bin/bash

UDP_IP=127.0.0.1
UDP_PORT=5000
PKT_SIZE=1316
BIT_RATE=4000000

rpicam-vid -t 0 --inline \
  --vflip --hflip \
  --nopreview \
  --libav-format h264 \
  --bitrate $BIT_RATE \
  --width 1280 --height 720 --framerate 30 \
  -o - \
| ffmpeg -fflags +genpts -use_wallclock_as_timestamps 1 \
    -f h264 -probesize 5M -analyzeduration 5M \
    -i - \
    -c copy -f mpegts "udp://$UDP_IP:$UDP_PORT?pkt_size=$PKT_SIZE"

